base_url = "https://blog.mickzh.com"

title = "針織拙見"

default_language = "zh-tw"

# Feeds
generate_feeds = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
    { name = "categories", feed = true},
    { name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_theme = "css"
highlight_code = true
external_links_target_blank = true
external_links_no_referrer = true

[slugify]
paths = "off"
taxonomies = "on"
anchors = "off"

[extra]
js_bundle_name = ["copy-code-button.js"]
